#!/bin/bash

DATABASE_HOST="$DATABASE_HOST"
DATABASE_USER_NAME="$DATABASE_USER_NAME"
DATABASE_PASSWORD="$DATABASE_PASSWORD"
DATABASE_NAME="recommend"
CSV_FILE="/home/ubuntu/movies.csv"

TABLE_NAME="movies"

SQL_QUERY=$(cat <<EOF
CREATE DATABASE IF NOT EXISTS $DATABASE_NAME;
USE $DATABASE_NAME;

DROP TABLE IF EXISTS $TABLE_NAME;
CREATE TABLE $TABLE_NAME (
    movieId INT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    genres VARCHAR(255)
);

LOAD DATA LOCAL INFILE '$CSV_FILE' 
    INTO TABLE $TABLE_NAME
    FIELDS TERMINATED BY ','
    OPTIONALLY ENCLOSED BY '"'
    LINES TERMINATED BY '\n'  
    IGNORE 1 ROWS
    (movieId, title, genres);
EOF
)

mysql --local-infile=1 -h "$DATABASE_HOST" -u "$DATABASE_USER_NAME" -p"$DATABASE_PASSWORD" <<< "$SQL_QUERY"
ROW_COUNT=$(mysql -h "$DATABASE_HOST" -u "$DATABASE_USER_NAME" -p"$DATABASE_PASSWORD" -N -e "SELECT COUNT(*) FROM $DATABASE_NAME.$TABLE_NAME;")

echo "Movies data has been ingested into table: $TABLE_NAME"
echo "$ROW_COUNT rows were ingested."
